DjangoWeb3/DjangoWeb3/urls.py
"""
Definition of urls for DjangoWeb3.
"""

from django.conf.urls import include, url
from django.contrib import admin
from  learning_logs  import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', DjangoWeb3.views.home, name='home'),
    # url(r'^DjangoWeb3/', include('DjangoWeb3.DjangoWeb3.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
    # url(r'^index/$', views.index, name='index'),
     url(r'', include('learning_logs.urls',namespace='learning_logs')),


]

DjangoWeb3/learning_logs/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    # 主页
    url(r'^$',views.index, name='index'),
    # 显示所有的主题
    url(r'^topic/$',views.topics, name='topics'),
    ]

DjangoWeb3/learning_logs/models.py
import os
os.environ.update({"DJANGO_SETTINGS_MODULE": "config.settings"})
from django.db import models

# Create your models here.
class Topic(models.Model):
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    def  __str__(self): 
       return self.text
   






class Entry(models.Model):
    topic=models.ForeignKey(Topic)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
   
    class Meta:
        verbose_name_plural='entries'

    def  __str__(self):
        return self.text[:50]+"..."

DjangoWeb3/learning_logs/views.py
from django.shortcuts import render
# from learning_logs.models import *
from . models import Topic
# from django.shortcuts import render_to_response

# Create your views here.

def index(request):
  
  #  return render_to_response('index.html')
  return render(request,'learning_logs/index.html')

def topics(request):
    topics=Topic.objects.order_by('date_added')
    content={'topics':topics}
    return render(request,'learning_logs/topics.html',content)

DjangoWeb3/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
<p>
    <a href="{% url 'learning_logs:index' %}">Learnig Log</a> - 
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>
    {% block content %}{% endblock content %}
</body>
</html>

DjangoWeb3/learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
 {% extends "learning_logs/base.html" %}
    {% block content %}
    <p>
        Learning Logs helps you keep...
    </p>
    {% endblock content%}
</body>
</html>

DjangoWeb3/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
 {% extends "learning_logs/base.html" %}
    {% block content %}
    <p>Topics:</p>
    <p>
        <ul>
            {% for topic in topics %}
            <li>
                {{ topic }}
            </li>
            {% empty %}
            <li>
                No topics have been added yet.
            </li>
            {% endfor%}
        </ul>
    </p>
    {% endblock content%}
</body>
</html>